// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project System
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faItemRequest from '@/i18n/item-request/fa.json';
import enItemRequest from '@/i18n/item-request/en.json';
import faPersonImport from '@/i18n/person-import/fa.json';
import enPersonImport from '@/i18n/person-import/en.json';
import faSystemSecurityPermissions from '@/i18n/system-security-permissions/fa.json';
import enSystemSecurityPermissions from '@/i18n/system-security-permissions/en.json';
import faSystemSecurityRolePermissions from '@/i18n/system-security-role-permissions/fa.json';
import enSystemSecurityRolePermissions from '@/i18n/system-security-role-permissions/en.json';
import faSystemSecurityRoles from '@/i18n/system-security-roles/fa.json';
import enSystemSecurityRoles from '@/i18n/system-security-roles/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'item-request': faItemRequest,
  'person-import': faPersonImport,
  'system-security-permissions': faSystemSecurityPermissions,
  'system-security-role-permissions': faSystemSecurityRolePermissions,
  'system-security-roles': faSystemSecurityRoles,
  },
  en: {
  'item-request': enItemRequest,
  'person-import': enPersonImport,
  'system-security-permissions': enSystemSecurityPermissions,
  'system-security-role-permissions': enSystemSecurityRolePermissions,
  'system-security-roles': enSystemSecurityRoles,
  },
} as const;
